FROM node:18-alpine AS Builder

WORKDIR /app

COPY package*.json ./
RUN npm install
COPY . .


FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/public/index.html ./public/index.html
COPY --from=builder /app/server.js ./server.js
EXPOSE 3000

CMD ["node", "server.js"]